name : Build and Commit

on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses:  lemonarc/jekyll-action@1.0.0
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '_site'
          author_name: Thibault DUPONCHELLE
          author_email: thibault.duponchelle@gmail.com
          message: 'Auto commit'
          pathspec_error_handling: ignore
          tag_push: '--force'
